name: Blazor CI/CD (GCP - Inactive)
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/Rob/**'
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_email: ${{secrets.GCP_EMAIL}}
          service_account_key: ${{secrets.GCP_KEY}}
          project_id: ${{secrets.PROJECT_ID}}
          export_default_credentials: true

      - name: Generate key
        run: echo $GCP_KEY > ~/key.json

      - name: Docker Build
        run: docker build -t robwillup/rob:latest src/Rob

      - name: Docker Tag
        run: docker tag robwillup/rob:latest us-west2-docker.pkg.dev/singular-glow-313017/robwillup/rob:latest

      - name: Docker Auth with GCP
        run: |
          docker login -u oauth2accesstoken -p "$(gcloud auth application-default print-access-token)" \
          https://us-west2-docker.pkg.dev

      - name: Docker Push
        run: docker push us-west2-docker.pkg.dev/singular-glow-313017/robwillup/rob:latest

      - name: Deploy Image
        run: |
          gcloud run deploy rob --image us-west2-docker.pkg.dev/singular-glow-313017/robwillup/rob:latest \
          --platform=managed --region=us-west2 --service-account=github@singular-glow-313017.iam.gserviceaccount.com
