name: Rob.Api CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Rob.Api/**'
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2 
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1
        with:        
          dotnet-version: 6.0.x                                
          include-prerelease: true
          
      - name: dotnet restore
        run: dotnet restore src/Rob.Api
      - name: dotnet build
        run: dotnet build src/Rob.Api -c Release
        
      - name: Docker Build
        run: docker build -t robwillup/rob.api:latest src/Rob.Api/
