name: Rob.Api CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2     
      
      - name: dotnet restore
        run: dotnet restore src/Rob.Api
